#!/bin/bash

#PROJECTS_DIR=$HOME/Projects/test_captainu
PROJECTS_DIR=$HOME/projects

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

# setup rails applications
restart_app() {
  if [ ! -d "$PROJECTS_DIR/$1/tmp" ]; then
    mkdir "$PROJECTS_DIR/$1/tmp"
  fi
  touch tmp/restart.txt
}

update_configs() {
  cd $PROJECTS_DIR/$1/config
  local configs
  configs="$(ls *.yml.example)"
  for config in $configs; do
    local name
    name="$(echo $config | cut -d '.' -f1)"
    cp $config "$name.yml"
  done
}

setup_rails_app() {
  if [ ! -d "$PROJECTS_DIR/$1" ]; then
    cd $PROJECTS_DIR/$1
  fi
  fancy_echo "Installing Ruby Version"
  rbenv install -s
  cd ..
  cd $1
  rbenv version
  gem install bundler

  fancy_echo "Create application tmp directory"
  mkdir -p tmp

  fancy_echo "Installing needed Gems"
  bundle config build.eventmachine --with-cppflags=-I$(brew --prefix openssl)/include
  bundle install
  rbenv rehash

  fancy_echo "Updating Config"
  update_configs $1
}

clean_app() {
  fancy_echo "Cleaning Up Old Versions"
  if [ -d "$PROJECTS_DIR/$1" ]; then
    rm -rf "$PROJECTS_DIR/$1"
  fi
}

# Clone our repos
clone_repo() {
  fancy_echo "Cloning $1"
  git clone git@github.com:captainu/"$1"
}

symlink_pow() {
  rm $HOME/.pow/$1
  ln -s "$PROJECTS_DIR/$1" $HOME/.pow/"$1"
}

create_and_seed_db() {
  fancy_echo "Preparing Database"
  cd "$PROJECTS_DIR/$1"
  if [ $1 != "communicator" ]; then
    bundle exec rake db:drop
    bundle exec rake db:create
    bundle exec rake db:schema:load
    bundle exec rake db:migrate
  fi
  if [ $1 == "communicator" ]; then
    bundle exec rake cassandra:create
    bundle exec rake cassandra: migrate
    RAILS_ENV=test bundle exec rake db:create
  fi
  #bundle exec rake db:seed
}

run_specs() {
  fancy_echo "Running Tests"
  cd $PROJECTS_DIR/$1
  bundle exec rake db:test:prepare
  bundle exec rake spec
}

clone_and_setup_app() {
  cd $PROJECTS_DIR
  fancy_echo "Setting up $1"
  echo ""
  clean_app $1
  clone_repo $1
  cd $PROJECTS_DIR/$1
  setup_rails_app $1
  create_and_seed_db $1
  symlink_pow $1
  restart_app $1
  run_specs $1
}

if [ ! -d "$HOME/.pow" ]; then
  mkdir $HOME/.pow
fi

if [ ! -d $PROJECTS_DIR ]; then
  fancy_echo "Creating $PROJECTS_DIR"
  mkdir -p $PROJECTS_DIR
fi

cd $PROJECTS_DIR

clone_and_setup_app 'captainu'
clone_and_setup_app 'teamlab'
clone_and_setup_app 'core-data-api'
clone_and_setup_app 'communicator'
clone_and_setup_app 'hermod'
clone_and_setup_app 'sendgrid-adapter'

# Open All the Apps
open http://captainu.dev
