#!/bin/sh

echo "Installing the heroku-accounts plugin for using multiple Heroku accounts..."
  heroku plugins:install git://github.com/ddollar/heroku-accounts.git

echo "Installing the heroku-config plugin for pulling config variables locally to be used as ENV variables ..."
  heroku plugins:install git://github.com/ddollar/heroku-config.git
