#!/usr/bin/env bash
### end common-components/bash-shebang

# Welcome to the linux laptop script! Be prepared to turn your laptop (or
# desktop, no haters here) into an awesome development machine.

fancy_echo() {
  local fmt="$1"
  shift
  printf "\n$fmt\n" "$@"
}

read -p "Enter your email to generate ssh key: " email

fancy_echo "Installing git, for source control management ..."
sudo apt install -y git

fancy_echo "Installing libraries for common gem dependencies ..."
sudo apt install -y libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libreadline-dev build-essential apt-transport-https ca-certificates

fancy_echo "Installing snapd canonical package manager"
sudo apt install -y snapd

fancy_echo "Installing Zoom-Client"
sudo snap install zoom-client

fancy_echo "Installing Postman API development environment"
sudo snap install postman

fancy_echo "Installing tmux, to save project state and switch between projects ..."
sudo apt install -y tmux

fancy_echo "Installing curl ..."
sudo apt install -y curl

fancy_echo "Installing Redis ..."
wget http://download.redis.io/redis-stable.tar.gz &&
  tar xvzf redis-stable.tar.gz &&
  cd redis-stable && make
sudo cp src/redis-server /usr/local/bin/
sudo cp src/redis-cli /usr/local/bin/

fancy_echo "Installing Ngrok ..."
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && unzip ngrok-stable-linux-amd64.zip && rm ngrok-stable-linux-amd64.zip

fancy_echo "Installing Sublime Text 3 ..."
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update && sudo apt install -y sublime-text

fancy_echo "Installing VS Code ..."
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor >microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt update && sudo apt install -y code

fancy_echo "Installing zsh ..."
sudo apt install -y zsh

fancy_echo "Installing chrome ..."
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt update
sudo apt install -y google-chrome-stable

fancy_echo "Generating ssh key"
ssh-keygen -b 4096 -t ed25519 -f /home/user/.ssh/key-ed25519 -q -N "" -C "$email"
sudo mv ~/.config/autostart/gnome-keyring-ssh.desktop ~/.config/autostart/gnome-keyring-ssh.backup
ssh-add /home/user/.ssh/key-ed25519

fancy_echo "Installing Docker"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

fancy_echo "Installing oh-my-zsh ..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

fancy_echo "Installing slack ..."
sudo snap install slack

fancy_echo "Installing vim ..."
sudo apt install -y vim

fancy_echo "Installing dns utils ..."
sudo apt-get install -y dnsutils

fancy_echo "Installing net tools .."
sudo apt install -y net-tools

fancy_echo "Install telnet ..."
sudo apt-get install telnet

fancy_echo "Installing screen ..."
sudo apt-get update sudo apt-get install screen

fancy_echo "Installing Terminator ..."
sudo apt install terminator

fancy_echo "Installing K9s"
sudo curl -sS https://webinstall.dev/k9s | bash

fancy_echo "Installing terraform ..."
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
# verify key
gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint

#Add the official HashiCorp repository to your system.
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    sudo tee /etc/apt/sources.list.d/hashicorp.list

sudo apt update
sudo apt install terraform -y
