#!/usr/bin/env bash

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Installing zsh ..."
  successfully sudo apt-get install -y zsh
  successfully sudo chmod -R 755 /usr/local/share/zsh/site-functions # Fix a zsh permissions bug

echo "Changing your shell to zsh ..."
  successfully chsh -s `which zsh`

