#!/usr/bin/env bash

echo "Copying public key to clipboard. Paste it into your Github account ..."
  cat ~/.ssh/id_rsa.pub | xclip
  open https://github.com/account/ssh

echo "Using apt-get to install OS packages so let's update it first ..."
  sudo apt-get update -y

echo "Installing OS packages. You will be prompted for your password ..."
  sudo apt-get install build-essential bison openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev -y

echo "Install Postgres, a great open source relational database ..."
  sudo apt-get install libpq5 libpq-dev postgresql -y

echo "Install Redis, a key-value database ..."
  sudo apt-get install redis-server -y

echo "Installing ack, a good way to search through files ..."
  sudo apt-get install ack -y

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  sudo apt-get install imagemagick --fix-missing -y

echo "Installing RVM (Ruby Version Manager) ..."
  bash < <( curl http://rvm.beginrescueend.com/releases/rvm-install-head )
  echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"' >> ~/.bash_profile
  source ~/.rvm/scripts/rvm

echo "Installing Ruby 1.9 and making it the default Ruby ..."
  rvm install 1.9.2-p180
  rvm use 1.9.2-p180 --default

echo "Installing Bundler for managing Ruby libraries ..."
  gem install bundler --no-rdoc --no-ri

echo "Installing Rails to write and run web applications ..."
  gem install rails --no-rdoc --no-ri

echo "Installing the Heroku gem to interact with the http://heroku.com API ..."
  gem install heroku --no-rdoc --no-ri

echo "Installing the Taps gem to push and pull SQL databases between development, staging, and production environments ..."
  gem install taps --no-rdoc --no-ri

echo "Installing Ruby gems to talk to the databases ..."
  gem install sqlite3 pg --no-rdoc --no-ri

