---

- name: ruby | Install chruby
  homebrew:
    name: chruby
  tags:
    - packages
    - ruby

- name: ruby | Install ruby-install
  homebrew:
    name: ruby-install
  tags:
    - packages
    - ruby

- name: ruby | Setup chruby
  lineinfile:
    dest: ~/.zshrc.local
    line: source /usr/local/share/chruby/chruby.sh
  tags:
    - packages
    - ruby

- name: ruby | Setup autoloading of ruby version via .ruby-version files
  lineinfile:
    dest: ~/.zshrc.local
    line: source /usr/local/share/chruby/auto.sh
  tags:
    - packages
    - ruby

- name: ruby | Ensure ruby_directory exists
  file:
    path: "{{ ruby_directory }}"
    group: admin
    mode: "u=rwx,g=rwx,o=rx"
    state: directory
    recurse: yes
  sudo: true
  tags:
    - packages
    - ruby

- name: ruby | Install ruby
  shell: "ruby-install --rubies-dir {{ ruby_directory }} --cleanup --no-reinstall ruby {{ ruby_version }}"
  register: _ruby_install
  changed_when: "'already installed' not in _ruby_install.stdout"
  tags:
    - packages
    - ruby

- name: ruby | Setup default ruby version
  lineinfile:
    dest: ~/.zshrc.local
    line: "chruby ruby-{{ ruby_version }}"
  tags:
    - packages
    - ruby

- name: ruby | Update rubygems
  shell: "{{ ruby_gem_executable }} update --system"
  changed_when: false
  tags:
    - packages
    - ruby

- name: ruby | Install bundler
  gem:
    name: bundler
    executable: "{{ ruby_gem_executable }}"
  tags:
    - packages
    - ruby

- name: ruby | Configure bundler parallelism
  shell: "{{ ruby_bundle_executable }} config --global jobs {{ ansible_processor_cores }}"
  changed_when: false
  tags:
    - packages
    - ruby

- name: ruby | Install awesome_print
  gem:
    name: awesome_print
    executable: "{{ ruby_gem_executable }}"
  tags:
    - packages
    - ruby

